package com.cineplex.entity;
// Generated May 22, 2012 3:29:20 PM by Hibernate Tools 3.2.1.GA

import java.text.NumberFormat;
import java.util.HashSet;
import java.util.Locale;
import java.util.Set;
import net.sf.jasperreports.engine.fill.SimpleTextFormat;

/**
 * Bioskop generated by hbm2java
 */
public class Bioskop implements java.io.Serializable {

    private Integer idBioskop;
    private String nama;
    private String alamat;
    private String telp;
    private Integer nomat;
    private Integer htm;
    private Integer jmt;
    private Integer nomat3d;
    private Integer htm3d;
    private Integer jmt3d;
    private Double latitude;
    private Double longitude;
    private Set studios = new HashSet(0);

    public Bioskop() {
    }

    public Bioskop(String nama, String alamat, String telp, Integer nomat, Integer htm, Integer jmt, Integer nomat3d, Integer htm3d, Integer jmt3d, Double latitude, Double longitude, Set studios) {
        this.nama = nama;
        this.alamat = alamat;
        this.telp = telp;
        this.nomat = nomat;
        this.htm = htm;
        this.jmt = jmt;
        this.nomat3d = nomat3d;
        this.htm3d = htm3d;
        this.jmt3d = jmt3d;
        this.latitude = latitude;
        this.longitude = longitude;
        this.studios = studios;
    }

    public Integer getIdBioskop() {
        return this.idBioskop;
    }

    public void setIdBioskop(Integer idBioskop) {
        this.idBioskop = idBioskop;
    }

    public String getNama() {
        return this.nama;
    }

    public void setNama(String nama) {
        this.nama = nama;
    }

    public String getAlamat() {
        return this.alamat;
    }

    public void setAlamat(String alamat) {
        this.alamat = alamat;
    }

    public String getTelp() {
        return this.telp;
    }

    public void setTelp(String telp) {
        this.telp = telp;
    }

    public Integer getNomat() {
        return this.nomat;
    }

    public void setNomat(Integer nomat) {
        this.nomat = nomat;
    }

    public Integer getHtm() {
        return this.htm;
    }

    public void setHtm(Integer htm) {
        this.htm = htm;
    }

    public Integer getJmt() {
        return this.jmt;
    }

    public void setJmt(Integer jmt) {
        this.jmt = jmt;
    }

    public Integer getNomat3d() {
        return this.nomat3d;
    }

    public void setNomat3d(Integer nomat3d) {
        this.nomat3d = nomat3d;
    }

    public Integer getHtm3d() {
        return this.htm3d;
    }

    public void setHtm3d(Integer htm3d) {
        this.htm3d = htm3d;
    }

    public Integer getJmt3d() {
        return this.jmt3d;
    }

    public void setJmt3d(Integer jmt3d) {
        this.jmt3d = jmt3d;
    }

    public Double getLatitude() {
        return this.latitude;
    }

    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    public Double getLongitude() {
        return this.longitude;
    }

    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    public Set getStudios() {
        return this.studios;
    }

    public void setStudios(Set studios) {
        this.studios = studios;
    }

    public String getNomat2() {
        NumberFormat f = NumberFormat.getCurrencyInstance(new Locale("in", "ID"));
        return f.format(nomat);
    }
    public String getJumat2() {
        NumberFormat f = NumberFormat.getCurrencyInstance(new Locale("in", "ID"));
        return f.format(jmt);
    }
    public String getHTM2() {
        NumberFormat f = NumberFormat.getCurrencyInstance(new Locale("in", "ID"));
        return f.format(htm);
    }
    public String getNomat3D2() {
        NumberFormat f = NumberFormat.getCurrencyInstance(new Locale("in", "ID"));
        return f.format(nomat3d);
    }
    public String getJumat3D2() {
        NumberFormat f = NumberFormat.getCurrencyInstance(new Locale("in", "ID"));
        return f.format(jmt3d);
    }
    public String getHTM3D2() {
        NumberFormat f = NumberFormat.getCurrencyInstance(new Locale("in", "ID"));
        return f.format(htm3d);
    }
}
