package com.cineplex.entity;
// Generated Jun 8, 2012 2:15:03 PM by Hibernate Tools 3.2.1.GA



/**
 * DetailPesanan generated by hbm2java
 */
public class DetailPesanan  implements java.io.Serializable {


     private String idDetailPesanan;
     private Pesanan pesanan;
     private Jadwal jadwal;
     private String noKursi;

    public DetailPesanan() {
    }

	
    public DetailPesanan(String idDetailPesanan) {
        this.idDetailPesanan = idDetailPesanan;
    }
    public DetailPesanan(String idDetailPesanan, Pesanan pesanan, Jadwal jadwal, String noKursi) {
       this.idDetailPesanan = idDetailPesanan;
       this.pesanan = pesanan;
       this.jadwal = jadwal;
       this.noKursi = noKursi;
    }
   
    public String getIdDetailPesanan() {
        return this.idDetailPesanan;
    }
    
    public void setIdDetailPesanan(String idDetailPesanan) {
        this.idDetailPesanan = idDetailPesanan;
    }
    public Pesanan getPesanan() {
        return this.pesanan;
    }
    
    public void setPesanan(Pesanan pesanan) {
        this.pesanan = pesanan;
    }
    public Jadwal getJadwal() {
        return this.jadwal;
    }
    
    public void setJadwal(Jadwal jadwal) {
        this.jadwal = jadwal;
    }
    public String getNoKursi() {
        return this.noKursi;
    }
    
    public void setNoKursi(String noKursi) {
        this.noKursi = noKursi;
    }




}


