package com.cineplex.entity;
// Generated May 22, 2012 3:29:20 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Film generated by hbm2java
 */
public class Film  implements java.io.Serializable , Comparable<Film> {


     private Integer idFilm;
     private String judul;
     private String sutradara;
     private String jenis;
     private String produser;
     private String produksi;
     private String sinopsis;
     private Integer durasi;
     private String pemirsa;
     private String gambar;
     private Set jadwals = new HashSet(0);

    public Film() {
    }

    public Film(String judul, String sutradara, String jenis, String produser, String produksi, String sinopsis, Integer durasi, String pemirsa, String gambar, Set jadwals) {
       this.judul = judul;
       this.sutradara = sutradara;
       this.jenis = jenis;
       this.produser = produser;
       this.produksi = produksi;
       this.sinopsis = sinopsis;
       this.durasi = durasi;
       this.pemirsa = pemirsa;
       this.gambar = gambar;
       this.jadwals = jadwals;
    }
   
    public Integer getIdFilm() {
        return this.idFilm;
    }
    
    public void setIdFilm(Integer idFilm) {
        this.idFilm = idFilm;
    }
    public String getJudul() {
        return this.judul;
    }
    
    public void setJudul(String judul) {
        this.judul = judul;
    }
    public String getSutradara() {
        return this.sutradara;
    }
    
    public void setSutradara(String sutradara) {
        this.sutradara = sutradara;
    }
    public String getJenis() {
        return this.jenis;
    }
    
    public void setJenis(String jenis) {
        this.jenis = jenis;
    }
    public String getProduser() {
        return this.produser;
    }
    
    public void setProduser(String produser) {
        this.produser = produser;
    }
    public String getProduksi() {
        return this.produksi;
    }
    
    public void setProduksi(String produksi) {
        this.produksi = produksi;
    }
    public String getSinopsis() {
        return this.sinopsis;
    }
    
    public void setSinopsis(String sinopsis) {
        this.sinopsis = sinopsis;
    }
    public Integer getDurasi() {
        return this.durasi;
    }
    
    public void setDurasi(Integer durasi) {
        this.durasi = durasi;
    }
    public String getPemirsa() {
        return this.pemirsa;
    }
    
    public void setPemirsa(String pemirsa) {
        this.pemirsa = pemirsa;
    }
    public String getGambar() {
        return this.gambar;
    }
    
    public void setGambar(String gambar) {
        this.gambar = gambar;
    }
    public Set getJadwals() {
        return this.jadwals;
    }
    
    public void setJadwals(Set jadwals) {
        this.jadwals = jadwals;
    }

    @Override
    public int compareTo(Film o) {
        return this.idFilm-o.getIdFilm();
    }




}


