package com.cineplex.entity;
// Generated Jun 8, 2012 4:48:47 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Holiday generated by hbm2java
 */
public class Holiday  implements java.io.Serializable {


     private Date holidayDate;

    public Holiday() {
    }

    public Holiday(Date holidayDate) {
       this.holidayDate = holidayDate;
    }
   
    public Date getHolidayDate() {
        return this.holidayDate;
    }
    
    public void setHolidayDate(Date holidayDate) {
        this.holidayDate = holidayDate;
    }




}


