package com.cineplex.entity;
// Generated May 22, 2012 3:29:20 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Jadwal generated by hbm2java
 */
public class Jadwal  implements java.io.Serializable {


     private Integer idJadwal;
     private Studio studio;
     private Film film;
     private Date tglMulai;
     private Date tglAkhir;
     private Boolean three;
     private String jam;
     private boolean status;
     private Set detailPesanans = new HashSet(0);

    public Jadwal() {
    }

	
    public Jadwal(Date tglMulai, Date tglAkhir, boolean status) {
        this.tglMulai = tglMulai;
        this.tglAkhir = tglAkhir;
        this.status = status;
    }
    public Jadwal(Studio studio, Film film, Date tglMulai, Date tglAkhir, Boolean three, String jam, boolean status, Set detailPesanans) {
       this.studio = studio;
       this.film = film;
       this.tglMulai = tglMulai;
       this.tglAkhir = tglAkhir;
       this.three = three;
       this.jam = jam;
       this.status = status;
       this.detailPesanans = detailPesanans;
    }
   
    public Integer getIdJadwal() {
        return this.idJadwal;
    }
    
    public void setIdJadwal(Integer idJadwal) {
        this.idJadwal = idJadwal;
    }
    public Studio getStudio() {
        return this.studio;
    }
    
    public void setStudio(Studio studio) {
        this.studio = studio;
    }
    public Film getFilm() {
        return this.film;
    }
    
    public void setFilm(Film film) {
        this.film = film;
    }
    public Date getTglMulai() {
        return this.tglMulai;
    }
    
    public void setTglMulai(Date tglMulai) {
        this.tglMulai = tglMulai;
    }
    public Date getTglAkhir() {
        return this.tglAkhir;
    }
    
    public void setTglAkhir(Date tglAkhir) {
        this.tglAkhir = tglAkhir;
    }
    public Boolean getThree() {
        return this.three;
    }
    
    public void setThree(Boolean three) {
        this.three = three;
    }
    public String getJam() {
        return this.jam;
    }
    
    public void setJam(String jam) {
        this.jam = jam;
    }
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }
    public Set getDetailPesanans() {
        return this.detailPesanans;
    }
    
    public void setDetailPesanans(Set detailPesanans) {
        this.detailPesanans = detailPesanans;
    }




}


