package com.cineplex.entity;
// Generated Jun 6, 2012 4:30:33 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Member generated by hbm2java
 */
public class Member  implements java.io.Serializable {


     private String email;
     private String password;
     private String name;
     private Date birthday;
     private String identityType;
     private String noIdentity;
     private Boolean gender;
     private Boolean role;
     private Set saldos = new HashSet(0);
     private Set pesanans = new HashSet(0);

    public Member() {
    }

	
    public Member(String email, String name, Date birthday, String identityType, String noIdentity) {
        this.email = email;
        this.name = name;
        this.birthday = birthday;
        this.identityType = identityType;
        this.noIdentity = noIdentity;
    }
    public Member(String email, String password, String name, Date birthday, String identityType, String noIdentity, Boolean gender, Boolean role, Set saldos, Set pesanans) {
       this.email = email;
       this.password = password;
       this.name = name;
       this.birthday = birthday;
       this.identityType = identityType;
       this.noIdentity = noIdentity;
       this.gender = gender;
       this.role = role;
       this.saldos = saldos;
       this.pesanans = pesanans;
    }
   
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }
    public String getIdentityType() {
        return this.identityType;
    }
    
    public void setIdentityType(String identityType) {
        this.identityType = identityType;
    }
    public String getNoIdentity() {
        return this.noIdentity;
    }
    
    public void setNoIdentity(String noIdentity) {
        this.noIdentity = noIdentity;
    }
    public Boolean getGender() {
        return this.gender;
    }
    
    public void setGender(Boolean gender) {
        this.gender = gender;
    }
    public Boolean getRole() {
        return this.role;
    }
    
    public void setRole(Boolean role) {
        this.role = role;
    }
    public Set getSaldos() {
        return this.saldos;
    }
    
    public void setSaldos(Set saldos) {
        this.saldos = saldos;
    }
    public Set getPesanans() {
        return this.pesanans;
    }
    
    public void setPesanans(Set pesanans) {
        this.pesanans = pesanans;
    }

    public String getJenisKelamin() {
        return this.getGender() ? "Laki-laki" : "Perempuan";
    }

    public String getRole2() {
        try {
            return this.getRole() ? "Admin" : "Member";
        } catch (Exception e) {
            return "";
        }

    }

}


