package com.cineplex.entity;
// Generated Jun 8, 2012 2:15:03 PM by Hibernate Tools 3.2.1.GA

import java.text.NumberFormat;
import java.util.Date;
import java.util.HashSet;
import java.util.Locale;
import java.util.Set;

/**
 * Pesanan generated by hbm2java
 */
public class Pesanan implements java.io.Serializable {

    private String idPesanan;
    private Member member;
    private String jam;
    private Date tanggal;
    private Integer hargaTotal;
    private Boolean cetak;
    private Date tglJual;
    private Set detailPesanans = new HashSet(0);

    public Pesanan() {
    }

    public Pesanan(String idPesanan, Date tglJual) {
        this.idPesanan = idPesanan;
        this.tglJual = tglJual;
    }

    public Pesanan(String idPesanan, Member member, String jam, Date tanggal, Integer hargaTotal, Boolean cetak, Date tglJual, Set detailPesanans) {
        this.idPesanan = idPesanan;
        this.member = member;
        this.jam = jam;
        this.tanggal = tanggal;
        this.hargaTotal = hargaTotal;
        this.cetak = cetak;
        this.tglJual = tglJual;
        this.detailPesanans = detailPesanans;
    }

    public String getIdPesanan() {
        return this.idPesanan;
    }

    public void setIdPesanan(String idPesanan) {
        this.idPesanan = idPesanan;
    }

    public Member getMember() {
        return this.member;
    }

    public void setMember(Member member) {
        this.member = member;
    }

    public String getJam() {
        return this.jam;
    }

    public void setJam(String jam) {
        this.jam = jam;
    }

    public Date getTanggal() {
        return this.tanggal;
    }

    public void setTanggal(Date tanggal) {
        this.tanggal = tanggal;
    }

    public Integer getHargaTotal() {
        return this.hargaTotal;
    }

    public void setHargaTotal(Integer hargaTotal) {
        this.hargaTotal = hargaTotal;
    }

    public Boolean getCetak() {
        return this.cetak;
    }

    public void setCetak(Boolean cetak) {
        this.cetak = cetak;
    }

    public Date getTglJual() {
        return this.tglJual;
    }

    public void setTglJual(Date tglJual) {
        this.tglJual = tglJual;
    }

    public Set getDetailPesanans() {
        return this.detailPesanans;
    }

    public void setDetailPesanans(Set detailPesanans) {
        this.detailPesanans = detailPesanans;
    }

    public String getHargaTotal2() {
        NumberFormat f = NumberFormat.getCurrencyInstance(new Locale("in", "ID"));
        return f.format(hargaTotal);
    }
}
