package com.cineplex.entity;
// Generated May 22, 2012 3:29:20 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Saldo generated by hbm2java
 */
public class Saldo  implements java.io.Serializable {


     private Integer idSaldo;
     private Member member;
     private Integer saldo;
     private Date tgl;

    public Saldo() {
    }

	
    public Saldo(Date tgl) {
        this.tgl = tgl;
    }
    public Saldo(Member member, Integer saldo, Date tgl) {
       this.member = member;
       this.saldo = saldo;
       this.tgl = tgl;
    }
   
    public Integer getIdSaldo() {
        return this.idSaldo;
    }
    
    public void setIdSaldo(Integer idSaldo) {
        this.idSaldo = idSaldo;
    }
    public Member getMember() {
        return this.member;
    }
    
    public void setMember(Member member) {
        this.member = member;
    }
    public Integer getSaldo() {
        return this.saldo;
    }
    
    public void setSaldo(Integer saldo) {
        this.saldo = saldo;
    }
    public Date getTgl() {
        return this.tgl;
    }
    
    public void setTgl(Date tgl) {
        this.tgl = tgl;
    }




}


