package com.cineplex.entity;
// Generated May 22, 2012 3:29:20 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Studio generated by hbm2java
 */
public class Studio  implements java.io.Serializable {


     private Integer idStudio;
     private Bioskop bioskop;
     private String nama;
     private String denah;
     private boolean status;
     private Set jadwals = new HashSet(0);

    public Studio() {
    }

	
    public Studio(boolean status) {
        this.status = status;
    }
    public Studio(Bioskop bioskop, String nama, String denah, boolean status, Set jadwals) {
       this.bioskop = bioskop;
       this.nama = nama;
       this.denah = denah;
       this.status = status;
       this.jadwals = jadwals;
    }
   
    public Integer getIdStudio() {
        return this.idStudio;
    }
    
    public void setIdStudio(Integer idStudio) {
        this.idStudio = idStudio;
    }
    public Bioskop getBioskop() {
        return this.bioskop;
    }
    
    public void setBioskop(Bioskop bioskop) {
        this.bioskop = bioskop;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public String getDenah() {
        return this.denah;
    }
    
    public void setDenah(String denah) {
        this.denah = denah;
    }
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }
    public Set getJadwals() {
        return this.jadwals;
    }
    
    public void setJadwals(Set jadwals) {
        this.jadwals = jadwals;
    }




}


